site:
  title: Bitcoin Programming with BitcoinJS, Bitcoin Core and LND
  start_page: bitcoinjs-guide::index.adoc
  url: https://bitcoinjs-guide.bitcoin-studio.com
  #url: file:///Users/steph/Desktop/Bitcoin/Projects/Bitcoin-Programming-with-BitcoinJS/www/build/site
  #url: http://127.0.0.1:8887/
  robots: allow
content:
  sources:
    #- url: .
    #  branches: [v4, v5]
    - url: git@github.com:bitcoin-studio/Bitcoin-Programming-with-BitcoinJS.git
      branches: [v4, v5]
ui:
  bundle:
    snapshot: true
    url: ./ui/build/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    #author: St√©phane Roche <bitcoin-studio@protonmail.com>
    description: 'Non-official Bitcoin Programming with BitcoinJS, Bitcoin Core and LND extensive guide'
    keywords: 'bitcoin, bitcoin core, lnd, lightning network, programming'
    codebaseurl: 'https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS/blob/master/code/'
runtime:
  fetch: true